name: Build WinForms EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore SKL1/RishtaManagerPro.csproj

      - name: Publish (single-file EXE)
        run: dotnet publish SKL1/RishtaManagerPro.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RishtaManagerPro-win-x64
          path: SKL1/bin/Release/net8.0-windows/win-x64/publish/*
